name: DB Validate & Drift

on:
  pull_request:
  push:
    branches: [ "main", "sprint/**", "chore/**", "feat/**", "fix/**" ]

jobs:
  db-validate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      PGHOST: 127.0.0.1
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      # Usuário/app DB (usado pelos scripts/Make)
      APP_DB_USER: anima
      APP_DB_PASS: anima
      APP_DB_NAME: anima
      DATABASE_URL: postgres://anima:anima@127.0.0.1:5432/anima?sslmode=disable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Create app role & db
        run: |
          psql -h $PGHOST -U $PGUSER -c "DO \$\$ BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${APP_DB_USER}') THEN
              CREATE ROLE ${APP_DB_USER} LOGIN PASSWORD '${APP_DB_PASS}' SUPERUSER;
            END IF;
          END \$\$;"
          psql -h $PGHOST -U $PGUSER -c "SELECT 1 FROM pg_database WHERE datname='${APP_DB_NAME}'" | grep -q 1 || \
          psql -h $PGHOST -U $PGUSER -c "CREATE DATABASE ${APP_DB_NAME} OWNER ${APP_DB_USER};"

      - name: Show psql versions
        run: |
          psql --version
          psql -h $PGHOST -U $PGUSER -c "SELECT version();"

      - name: Validate migrations
        run: |
          make db-validate

      - name: Drift check
        run: |
          make db-drift
