name: Validate Migrations
on:
  pull_request:
    paths: ["db/migrations/**","tools/**",".github/workflows/migrations.yml","Makefile"]
  push: { branches: [ main ] }
jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env: { POSTGRES_USER: anima, POSTGRES_PASSWORD: anima, POSTGRES_DB: anima }
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U anima"
          --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }
      - name: Install migrate
        run: go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - name: Env
        run: echo "DATABASE_URL=postgres://anima:anima@localhost:5432/anima?sslmode=disable\nTEST_DB=anima_migrate_check" > .env
      - name: Validate
        run: chmod +x tools/*.sh && make ci-validate
